import { type NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useRouter } from "next/router";
import HomePage from "../components/HomePage";

const Home: NextPage = () => {
  const { data: hello } = trpc.test.test.useQuery("asd");
  const { data: hello2 } = trpc.test.server.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage>
        <div>{hello}</div>
        <div>{hello2}</div>
      </HomePage>
    </>
  );
};

//getcurrent url in nextjs

export default Home;
